### ISSUE TITLE
rutracker и прочие закрытые трекеры

### ISSUE THREAD

**Issue by luuluuu** [Nemiroff/script.elementum.nova#12]
Сейчас есть проблемы с поиском торрентов на заблокированных трекерах (например, рутрекер, кинозал и т.п.) - торренты не находятся.
В настройках есть опция указать альтернативный адрес - но она тоже не помагает.

Сейчас для рутрекера есть собственное зеркало, которое, естественно, не заблокировано. Но даже если это зеркало указываю как альтернативный домен - все равно торренты на рутрекере не находит.
Есть ли возможность добавить опцию, чтобы плагин в первую очередь обращался к указанному вручную альтернативному адресу?

**Comment by Nemiroff** [comment]
Все так и работает. Если указан альтернативный адрес, то обращение идёт к нему. Кроме одного случая: если включён обход через OpenNIC. В этом случае обращение идёт к lib зоне в любом случае
