### ISSUE TITLE
Изменение цвета

### ISSUE THREAD

**Issue by PostnikovArtem** [Nemiroff/script.elementum.nova#14]
Здравствуйте! Подскажите, пожалуйста, как в вашем плагине поменять цвет у разрешения в поиске торрентов?
![Z4zQW8E_ELo](https://user-images.githubusercontent.com/27950783/74480828-b1b0d700-4ec2-11ea-85b1-f7f943e9e238.jpg)

**Comment by Nemiroff** [comment]
Никак. Это элементум окрашивает разрешение

**Comment by PostnikovArtem** [comment]
А у вас нету случайно предположений какой файл элементума отвечает за цвета? Уже весь исходный код перерыл.. Изменить можно все, кроме разрешений. Их даже в парсинге нету
