### ISSUE TITLE
Поддержка antizapret для обхода блокировки?

### ISSUE THREAD

**Issue by byaka** [Nemiroff/script.elementum.nova#3]
Былобы здорово добавить поддержку непосредственно в плагин (как например в плагине rutor)

**Comment by Nemiroff** [comment]
1. Так же требуется поддержка со стороны elementum.
2. Torrent движок не поддерживает прокси.

**Comment by byaka** [comment]
Извиняюсь если скажу глупость - но разве не нова занимается загрузкой страниц и их парсингом, а далее просто передает ссылку на торрент файл (или магнет) в элементум? Если так, то поддержка нужна только на этапе работы с сайтом, элементуму и темболее торрент клиенту это ненужно. Сейчас я например захожу на тотже рутор через прокси, копирую ссылку и добавляю ее в елементум который работает напрямую.

**Comment by Nemiroff** [comment]
Не все так просто. Нова ищет раздачи и передает ссылку!!! на скачивание torrent elementum. Последний уже скачивает torrent файл по ссылке и воспроизводит его. Если нова передаст ссылку, а elementum её скачать не сможет - чудо не произойдет...

**Comment by byaka** [comment]
Да, именно об этом я и говорю. Только что проверил еще раз - магнет ссылки и торрент файлы не блокированы. Проверял на руторе, провайдер onlime.

**Comment by Nemiroff** [comment]
Вы видимо не понимаете все таки весь механизм.. не  будет оно работать с одной стороны. Поддержка нужна сразу в 2х плагинах

**Comment by byaka** [comment]
ок, спасибо
