### ISSUE TITLE
Язык для поиска по LostFilm

### ISSUE THREAD

**Issue by unclev** [Nemiroff/script.elementum.nova#5]
Кажется, провайдер **LostFilm** сломан из-за этого 
https://github.com/Nemiroff/script.elementum.nova/blob/0f6b4e79839785ab147890670585c1e85cd3f52e/nova/filtering.py#L316-L319
lostfilm ожидает url поиска в виде `series/{title:original}/season_{season}/episode_{episode}/`

Кодом выше `use_language = 'ru'`, что даёт неверный url, например, `series/легион/season_2/episode_1/`.

Полагаю, `use_language = self.kodi_language` нужно только если `use_language` не задан явно ранее.

```diff
diff --git a/nova/filtering.py b/nova/filtering.py
index acb9b32..838711e 100644
--- a/nova/filtering.py
+++ b/nova/filtering.py
@@ -313,7 +313,7 @@ class Filtering:
                    (use_language or self.kodi_language) and \
                    'titles' in self.info and self.info['titles']:
                     try:
-                        if self.kodi_language and self.kodi_language in self.info['titles']:
+                        if not use_language and self.kodi_language and self.kodi_language in self.info['titles']:
                             use_language = self.kodi_language
                         if use_language not in self.info['titles']:
                             use_language = language
```

**Comment by unclev** [comment]
Извините, не вспомнил об обычной практике. Пожалуйста, - [kodi.log](http://paste.ubuntu.com/p/8hnWbR69yd/), только значения cookies вымарал.

**Comment by Nemiroff** [comment]
В настройках новы включена опция Дополнительно - Использовать язык Kodi когда доступен перевод ?

**Comment by unclev** [comment]
ИМХО, неочевидная настройка, которая, «внезапно» влияет глобально на подготову url-ов провайдеров. Кому-то нужно, наверно... Спасибо. Пофиксил.

**Comment by Nemiroff** [comment]
Эта настройка осталась со времен Quasar Burst и работала правильно до тех пор, пока в providers.json не стали появляться ключи вроде title:original. 
На Lostfilm она повлияла в виду особенностей поиска на лостфильме через url, а не через поисковый запрос.
